describe('tests for tiny-templates.nvim', function()
     it('creates a new buffer initialized with a template', function()
        require('tiny-templates')
        vim.cmd('edit test.lua')
        local buf = vim.fn.bufadd('test.lua')
        assert(vim.api.nvim_buf_line_count(buf) > 0, 'there are no lines!')
     end)
     it('creates an empty buffer', function()
         vim.cmd('edit test.txt')
         local buf = vim.fn.bufadd('test.txt')
         assert(vim.api.nvim_buf_line_count(buf) <= 1, 'buffer should be empty')
     end)
end)

